//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int idHistorial { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public Nullable<int> IdTratamiento { get; set; }
        public Nullable<int> idobrasocial { get; set; }
        public Nullable<decimal> pago { get; set; }
        public string tratamiento { get; set; }
        public Nullable<byte> dia { get; set; }
        public Nullable<byte> mes { get; set; }
        public Nullable<short> ano { get; set; }
        public Nullable<int> idturno { get; set; }
    }
}
