//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcione
    {
        public int Id { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> pacientes_x_sobreturno { get; set; }
        public string nombre_registro { get; set; }
        public string password { get; set; }
        public Nullable<int> color_libre { get; set; }
        public Nullable<int> color_compartido { get; set; }
        public Nullable<int> color_ocupado { get; set; }
        public Nullable<int> color_sobreturno { get; set; }
        public Nullable<int> auto_refresh { get; set; }
        public Nullable<int> pacientes_x_primera_sesion { get; set; }
        public Nullable<int> color_rpg_libre { get; set; }
        public Nullable<int> color_rpg_vino { get; set; }
        public Nullable<int> color_rpg_ocupado { get; set; }
        public string NombreConsultorio { get; set; }
        public string PieReporte { get; set; }
        public string DatosConsultorio { get; set; }
        public string tamNombre { get; set; }
        public string tamPie { get; set; }
        public string tamDatos { get; set; }
        public Nullable<int> modo_15_minutos { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_backup { get; set; }
        public Nullable<int> conf_tiempo_tfk { get; set; }
        public Nullable<int> pacientes_x_turno { get; set; }
        public Nullable<int> limite_de_ausentes { get; set; }
    }
}
