//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Aseguradora_Historico
    {
        public int ID { get; set; }
        public int PacienteID { get; set; }
        public int AseguradoraPlanID { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public bool Habilitado { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Aseguradora_Plan Aseguradora_Plan { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
