//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Imagens = new HashSet<Imagen>();
            this.Paciente_Aseguradora_Historico = new HashSet<Paciente_Aseguradora_Historico>();
            this.Turnoes = new HashSet<Turno>();
        }
    
        public int ID { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Celular { get; set; }
        public int AseguradoraID { get; set; }
        public Nullable<int> AseguradoraPlanID { get; set; }
        public string DocumentoNumero { get; set; }
        public Nullable<int> DocumentoTipoID { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> ProvinciaID { get; set; }
        public Nullable<int> LocalidadID { get; set; }
        public string NumeroAfiliado { get; set; }
        public string NumeroHC { get; set; }
        public string Observaciones { get; set; }
        public bool Habilitado { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<bool> EsGravado { get; set; }
        public string ObraSocial { get; set; }
        public string CodigoSeguridad { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual Aseguradora_Plan Aseguradora_Plan { get; set; }
        public virtual Documento_Tipo Documento_Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagens { get; set; }
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente_Aseguradora_Historico> Paciente_Aseguradora_Historico { get; set; }
        public virtual Provincia Provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turnoes { get; set; }
    }
}
