//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class repeticionesMedico
    {
        public string nombre { get; set; }
        public Nullable<int> idMedico { get; set; }
        public bool lun { get; set; }
        public bool mar { get; set; }
        public bool mie { get; set; }
        public bool jue { get; set; }
        public bool vie { get; set; }
        public bool sab { get; set; }
        public int idrepeticion { get; set; }
    }
}
