//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int IdTratamiento { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string derivador { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<int> cantsesiones { get; set; }
        public string otros { get; set; }
    }
}
