//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sgt.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno_Repeticiones
    {
        public int ID { get; set; }
        public int TurnoID { get; set; }
        public int Posicion { get; set; }
        public int DiaSemana { get; set; }
        public int ConsultorioID { get; set; }
        public System.DateTime Hora { get; set; }
        public int Frecuencia { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Modulos { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
